### ISSUE TITLE
use of screen command makes kubctl/docker logs invisible

### ISSUE THREAD

**Issue by thehajime** [fed4iot/VirIoT#10]
I'm trying to implement CI (by github actions) and would like to verify if thing visor deployment is working well or not by conducting something like this

```
kubect logs tv-f4i-hello-world |grep vThing/helloWorld/hello/data_out
```

but current command (start.sh) uses `screen` command, which `kubectl logs` command shows nothing without attaching container and screen.

https://github.com/fed4iot/VirIoT/blob/73e058a13ee05aaa12782b83c8d96d4bb4cfc767/Thingvisors/DockerThingVisor/ThingVisor_HelloWorld/start.sh#L3-L4

Except debug/development purpose, do you have any intention to use the screen command for the container instance ? If not, is it possible to remove this ?

**Comment by gtropea** [comment]
maybe you could try to monitor wether the TV is publishing by doing a specific subscription:
```bash
mosquitto_sub -v -h [MQTT_SERVER_IP] -p 1883 -t 'vThing/helloWorld/hello/data_out'
```

**Comment by fed4iot** [comment]
We used screen in vSilo Flavours because they run both the controller and the broker. One screen for each. In this way it is simple, if something goes wrong, to enter the container and get in the screen to see what went wrong. Without screen, the container was lost immediately and we would have no idea why. Same motivations for the ThingVisor. I think that if you want to see what the TV is doing you can use  kubectl exec <pod-name> -it bash
 and then screen -r

**Comment by gtropea** [comment]
I think Hajime wants some **automated** means to check if the TV is producing something, in order to implement some Continuous Integration (CI) workflow via github actions.

**Comment by thehajime** [comment]
> maybe you could try to monitor wether the TV is publishing by doing a specific subscription:
> 
> ```shell
> mosquitto_sub -v -h [MQTT_SERVER_IP] -p 1883 -t 'vThing/helloWorld/hello/data_out'
> ```

yep this is okay for the case to check the activity.

I faced the other case that with some reason, master-controller.py isn't ready to listen 8090 port.
After trial of dozen of github action trial, it seems like the master-controller.py can't connect to mongo db, with the following message (this is collected from my local machine, which I have *terminal* access. on Github action or some CI environments, terminal access isn't often available (We can't `kubectl exec + screen -r`)).


```
Traceback (most recent call last):
  File "/app/thingVisor_hello.py", line 211, in <module>
    port_mapping = db[thing_visor_collection].find_one({"thingVisorID": thing_visor_ID}, {"port": 1, "_id": 0})
  File "/usr/lib/python3.5/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python3.5/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python3.5/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/usr/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/lib/python3.5/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/usr/lib/python3.5/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: db-svc-mc-noauth.default.svc.cluster.local:27017: [Errno -3] Try again
```

In this case, it may be some configuration error of k8s etc, but those kind of in stdout/stderr information is super helpful to handle unexpected cases of errors, which is a reason why kubectl/docker logs commands exist.



@fed4iot,
> In this way it is simple, if something goes wrong, to enter the container and get in the screen to see what went wrong. Without screen, the container was lost immediately and we would have no idea why.

I guess (I didn't test though) that if you dont remove the instance after the execution (if you don't `docker run --rm` or alike), kubectl/docker logs command can print what's wrong.

This is a useful way to investigate errors when we don't have terminal access (without tty) on typical CI environment.  I understand the usefulness of screen command, but wondering if there is a familiar way for the tty-less environment.

**Comment by gtropea** [comment]
@thehajime 
Concerning the db connection, you write:
```bash
Traceback (most recent call last):
  File "/app/thingVisor_hello.py", line 211, in <module>
    port_mapping = db[thing_visor_collection].find_one({"thingVisorID": thing_visor_ID}, {"port": 1, "_id": 0})
```
It seems to me it is the Hello ThingVisor (thingVisor_hello.py) the one having problems connecting/authorizing with mongoDB, **not** the master-controller.py. Have you tried another TV, e.g. the Weather TV ? Does it have the same issue?

**Comment by thehajime** [comment]
@gtropea ah, maybe this is not a good example.  but I just wanted to say that those kind of python output will be hidden with current master controller pod by screen command.

**Comment by thehajime** [comment]
what about adding `screen -x` instead of `sleep infinity` ?

**Comment by gtropea** [comment]
yes, could work, but in this case we should omit the "-d -m" options when creating the one screen that we want to see the stout of. This way "screen -x" (as last line of start.sh) should attach to that "not detached" screen we omitted "-d -m" of.

**Comment by gtropea** [comment]
@thehajime Sorry did a quick try, but it **did not** work. Yes, I ended up with one Attached screen, but the start.sh script did not go well, the commands were not executed and when i did
```bash
docker exec -it [SILO_CONTAINER_NAME] /bin/bash
```
I still was seeing the outer prompt's output, not the Attached screen's one...
