### ISSUE TITLE
if /addFlavor API fails, there is no error message response

### ISSUE THREAD

**Issue by gtropea** [fed4iot/VirIoT#12]
The /addFlavour POST handler in recv_add_flavour() method of master-controller.py spawns a new Thread to create the flavour and always exits with a graceful "flavour is being created" message. So, if the new Thread fails to create the Flavour (e.g. docker image not found), the user is not immediately notified. Even if he wants to use the /inspectFlavour to inspect the status, no flavourID is found, because it was immediately removed upon failure by the Thread: there is nothing to inspect.
The user will never know the reason why the /addFlavour failed (unless monitoring stdout of master-controller.py)

**Comment by gtropea** [comment]
basically it means that the "except docker.errors.ImageNotFound:" (as well as all other except) in recv_add_flavour() method cannot ever be raised...

**Comment by fed4iot** [comment]
It is fire&forget approach we used in every API. The Master Controller immediately gives back you the answer "I am doing something" then it is up to you to control with list-flavours (etc) the status. We use this approach because otherwise you can remain attached e.g. for all the time needed to pull a fat image.

**Comment by gtropea** [comment]
yes, docker.pull of flavour image must be fire&forget.
But if you fail immediately without pulling anything because my image name was wrong, then you have to tell me...
My user experience was: 1) /createFlavour "foo" 2) your answer is: "check flavours to see how it is going" 3) I check flavours and I don't find anything
