### ISSUE TITLE
2nd add-thingvisor fails if there is already one thingVisor added

### ISSUE THREAD

**Issue by thehajime** [fed4iot/VirIoT#13]
### steps to reproduce
1. add a thingVisor `./f4i.py add-thingvisor -y ../yaml/thingVisor-helloWorld.yaml`,
(it goes well with a deployed pod, generating messages)
1. add another tv  (`./f4i.py add-thingvisor -y ../yaml/thingVisor-weather.yaml`) after that
1. it won't add the thingvisor with the following message:

```
Adding Thing Visor, please wait ....
<class 'generator'>
{'debug_mode': False,
 'description': 'hello thingVisor',
 'imageName': '',
 'params': '',
 'thingVisorID': 'helloWorld',
 'tvZone': '',
 'yamlsFile': [{'apiVersion': 'apps/v1',
                'kind': 'Deployment',
                'metadata': {'name': 'f4i-tv-weather'},
                'spec': {'replicas': 1,
                         'selector': {'matchLabels': {'app': 'f4i-tv-weather'}},
                         'template': {'metadata': {'labels': {'app': 'f4i-tv-weather'}},
                                      'spec': {'containers': [{'image': 'fed4iot/v-weather-tv:2.2',
                                                               'name': 'wheater',
                                                               'ports': [{'containerPort': 8089}]}]}}}}]}
Add fails - thingVisor helloWorld already exists
```

The github action with this reproduced one is available below (you need to login github to view logs).

https://github.com/thehajime/VirIoT/runs/489183075?check_suite_focus=true#step:6:84

The problems I see are:
1. why thingVisorID is 'helloworld' on the 2nd operation ?
1. even this failure, `f4i.py` doesn't tell errors to the CLI, thus can't detect error on CI

Let me know if I misunderstand the operation here.

(The github action is still under development, which may need to resolve #10 at least)

**Comment by ludovicofunari** [comment]
This can be easily avoided using the argument `-n <thing_visor_id>` . As a matter of fact, you can see that if you run the command with the `--help` flag, the default ThingVisor ID is "helloWorld".
```
usage: f4i.py add-thingvisor [-h] [-c CONTROLLERURL] [-i IMAGENAME] [-n NAME]
                             [-p PARAMS] [-d DESCRIPTION] [-y YAMLSFILEPATH]
                             [-z TVZONE] [--debug]

optional arguments:
  -h, --help        show this help message and exit
  -c CONTROLLERURL  Controller url (default: http://127.0.0.1:8090)
  -i IMAGENAME      image name (default: "")
  -n NAME           ThingVisor ID (default: helloWorld)
  -p PARAMS         ThingVisor params, JSON object (default: "")
  -d DESCRIPTION    ThingVisor description (default: hello thingVisor)
  -y YAMLSFILEPATH  yamlsFilePath (default: no yamls file)
  -z TVZONE         Zone in which the ThingVisor will be deployed
  --debug           debug mode, boolean (default: false)

```

That's why if you add two ThingVisors without the name argument, it will fail to deploy the second one as they have the same flavours ID: "helloWorld".

**Comment by thehajime** [comment]
@ludfun Thanks, now I understand the system better :)
